/*
	Copyright (c) openheap, uplusware
	uplusware@gmail.com
*/

#ifndef __POSIXNAME__
#define __POSIXNAME__

#define NIUHTTPD_POSIX_PREFIX          "/.NIUHTTPD_"

#define NIUHTTPD_POSIX_QUEUE_SUFFIX        ".que"
#define NIUHTTPD_POSIX_SEMAPHORE_SUFFIX    ".sem"

#define NIUHTTPD_GLOBAL_REJECT_LIST    NIUHTTPD_POSIX_PREFIX "GLOBAL_REJECT_LIST" NIUHTTPD_POSIX_SEMAPHORE_SUFFIX
#define NIUHTTPD_GLOBAL_PERMIT_LIST    NIUHTTPD_POSIX_PREFIX "GLOBAL_PERMIT_LIST" NIUHTTPD_POSIX_SEMAPHORE_SUFFIX

#define NIUHTTPD_SERVICE_LOGNAME       "/var/log/niuhttpd/service.log"
#define NIUHTTPD_SERVICE_LCKNAME       NIUHTTPD_POSIX_PREFIX "SERVICE_LOG" NIUHTTPD_POSIX_SEMAPHORE_SUFFIX

#define NIUHTTPD_SSLERR_LOGNAME        "/var/log/niuhttpd/sslerr.log"
#define NIUHTTPD_SSLERR_LCKNAME        NIUHTTPD_POSIX_PREFIX "SSLERR_LOG" NIUHTTPD_POSIX_SEMAPHORE_SUFFIX
    
#endif /* __POSIXNAME__ */