/*
	Copyright (c) openheap, uplusware
	uplusware@gmail.com
*/

#ifndef __POSIXNAME__
#define __POSIXNAME__

#define HEAPHTTPD_POSIX_PREFIX          "/.HEAPHTTPD_"

#define HEAPHTTPD_POSIX_QUEUE_SUFFIX        ".que"
#define HEAPHTTPD_POSIX_SEMAPHORE_SUFFIX    ".sem"

#define HEAPHTTPD_GLOBAL_REJECT_LIST    HEAPHTTPD_POSIX_PREFIX "GLOBAL_REJECT_LIST" HEAPHTTPD_POSIX_SEMAPHORE_SUFFIX
#define HEAPHTTPD_GLOBAL_PERMIT_LIST    HEAPHTTPD_POSIX_PREFIX "GLOBAL_PERMIT_LIST" HEAPHTTPD_POSIX_SEMAPHORE_SUFFIX

#define HEAPHTTPD_SERVICE_LOGNAME       "/var/log/heaphttpd/service.log"
#define HEAPHTTPD_SERVICE_LCKNAME       HEAPHTTPD_POSIX_PREFIX "SERVICE_LOG" HEAPHTTPD_POSIX_SEMAPHORE_SUFFIX

#define HEAPHTTPD_SSLERR_LOGNAME        "/var/log/heaphttpd/sslerr.log"
#define HEAPHTTPD_SSLERR_LCKNAME        HEAPHTTPD_POSIX_PREFIX "SSLERR_LOG" HEAPHTTPD_POSIX_SEMAPHORE_SUFFIX
    
#endif /* __POSIXNAME__ */